{% set version = "0.5.9" %}
{% set hash_value = "6eaca78e53fbe329b163f0f0b28f104de98edbd69a847268cc5d6a6e392b9b28" %}

package:
  name: wand
  version: '{{ version }}'

source:
  url: https://github.com/emcconville/wand/releases/download/{{ version }}/Wand-{{ version }}.tar.gz
  sha256: '{{ hash_value }}'

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - python
    - pip

  run:
    - python
    - imagemagick

test:
  imports:
    - wand.image

about:
  home: https://github.com/emcconville/wand
  license: MIT
  summary: 'Wand is a ctypes-based simple ImageMagick binding for Python, supporting 2.7, 3.6+, and PyPy'
  license_file: LICENSE
  license_family: MIT

extra:
  recipe-maintainers:
    - r78v10a07
