
{% set version = "0.6.10" %}

package:
  name: wand
  version: {{ version }}

source:
  url: https://github.com/emcconville/wand/releases/download/{{ version }}/Wand-{{ version }}.tar.gz
  sha256: 373f4a7f2866c868c31ce910e1f9b36a92d132640a20068ec17cea3284fedc57


build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - python >=3.3|>=2.7
    - pip

  run:
    - python >=3.3|>=2.7
    - imagemagick

test:
  imports:
    - wand.image

about:
  home: https://github.com/emcconville/wand
  license: MIT
  summary: Wand is a ctypes-based simple ImageMagick binding for Python, supporting 2.7, 3.6+, and PyPy
  license_file: LICENSE
  license_family: MIT

extra:
  recipe-maintainers:
    - melonhead901
    - r78v10a07
