travis:
  secure:
    BINSTAR_TOKEN: OiRBePoSDstV3bgt5EmxCwq/QQFPQMnxfvS96tkFsKMTrwnAaDGiIN+ZQ/ZKIvMmPQn94OGfV9L2GCJlt+zeLv6sjzICd0RW6/D2iMmsqwjcHTKudKrK+3oytv3hz0FQp3zeVkCIb5yhLrzfzaZkHYBOyt/gLuEr2ZeuUZuc0BA82M+ICyZlhQjzRS39JqUkP7kh62P8eqdhbNxwPWYPa5yD0/NdUc/Isu6mJQVaU8pTUux8AcMEhjvp+MGmfNQwHgh1APnGXqibJKTCfJlI2WCLTe/GGzJcluSMvLwbIOFZ+N0rOz79Z6WCnpS5yucUYWLhtWg5mFO2cMw21HOJuuhabdNfJG4fM/l96FPFxzVhZWeghytIn9QqQhktu+eoOZ+CQ+WH4cQ1rvmFUbuHeICTsyc+YbgS1J/8oIgxQ0D/nmGewB28sqnKmc76Su9237kkWIw3BO1tUNj/yDH3kVQBheJ8xPjRLsOQtJTqAvNENIhg4r5ZNT6jpBqXmEdO0buTNeLWPNl+wbbS96prnFjQc6RldUzy8SmwOIu6Gt/yNehdQAG2hq2qyCcJfZp1p/+h6K29GIFhADOkTBJ8onwApCoSHQkAwcwHVtdMSDsWFMzuDncvn7Ft8qofqxbw9bvAclZYu/6JSauwnBh0R2OlOlDKvx5S8bw40GZamS0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
